# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-13 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ct_name', models.CharField(default=b'DEFAULT VALUE', max_length=30)),
                ('ct_country', models.CharField(blank=True, default=b'DEFAULT VALUE', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(default=b'DEFAULT VALUE', max_length=128)),
                ('user', models.CharField(blank=True, default=b'DEFAULT VALUE', max_length=30, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(default=b'DEFAULT VALUE', max_length=30)),
                ('c_url_photo', models.URLField(blank=True, default=b'DEFAULT VALUE', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(default=b'DEFAULT VALUE', max_length=30)),
                ('g_organiser', models.CharField(default=b'DEFAULT VALUE', max_length=30)),
                ('g_member', models.IntegerField(default=b'DEFAULT VALUE', max_length=100)),
                ('g_place', models.CharField(default=b'DEFAULT VALUE', max_length=30)),
                ('g_city', models.CharField(default=b'DEFAULT VALUE', max_length=30)),
                ('g_content', models.TextField(blank=True, max_length=100, null=True)),
                ('g_state', models.CharField(default=b'DEFAULT VALUE', max_length=1)),
                ('g_country', models.CharField(default=b'DEFAULT VALUE', max_length=30)),
                ('g_createdtime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.CharField(blank=True, default=b'DEFAULT VALUE', max_length=30, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_group', to='books.Group')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default=b'DEFAULT VALUE', max_length=100)),
                ('username', models.CharField(default=b'DEFAULT VALUE', max_length=30)),
                ('password', models.CharField(default=b'DEFAULT VALUE', max_length=128)),
                ('firstname', models.CharField(default=b'DEFAULT VALUE', max_length=30)),
                ('lastname', models.CharField(default=b'DEFAULT VALUE', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_comment', to='books.Group'),
        ),
    ]
